name: Set Logs

on:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  time-logs:
    runs-on: ubuntu-22.04
    container:
      image: rkrispin/data-pipeline-automation-with-github-actions:prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "main"


      - name: Set execute permission for set_log.sh
        run: chmod +x ./LOGS/set_log.sh

      - name: Set logs
        run: bash ./LOGS/set_log.sh
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME }}

